const http=require("http");const WebSocket=require("ws");
const PORT=Number(process.env.PORT||3000),START=Number(process.env.PAPER_START_CAPITAL||10000);
const SCAN_MS=1000,COOLDOWN_MS=300000,FEE=.0004,SLIP=.0002,MAX_POS=12,MAX_SIDE=6,MARGIN=100,LEV=5,TP=.006,SL=.004,HOLD=900000;
let symbols=new Map(),ticks=new Map(),hist=new Map(),cool=new Map(),pos=new Map(),trades=[],equity=START,realized=0,scanNo=0,connected=false,lastScanMs=0,lastScanAt=0,topSignals=[],errors=0;
const now=()=>Date.now(), pct=(a,b)=>b?(a/b-1)*100:0;
async function getJSON(u){const r=await fetch(u);if(!r.ok)throw Error(r.status+" "+u);return r.json()}
async function universe(){const d=await getJSON("https://fapi.binance.com/fapi/v1/exchangeInfo");for(const s of d.symbols||[])if(s.status==="TRADING"&&s.quoteAsset==="USDT"&&s.contractType==="PERPETUAL")symbols.set(s.symbol,s)}
function tick(s,p,v,ts){if(!(p>0))return;ticks.set(s,{price:p,volume:v,ts});let h=hist.get(s);if(!h)hist.set(s,h=[]);h.push({ts,price:p});while(h.length&&ts-h[0].ts>60000)h.shift()}
function feat(s){const t=ticks.get(s),h=hist.get(s)||[];if(!t||h.length<2)return null;const p=t.price,ts=t.ts;const ret=w=>{for(let i=h.length-1;i>=0;i--)if(ts-h[i].ts>=w)return pct(p,h[i].price);return 0};const r1=ret(1000),r2=ret(2000),r5=ret(5000),r15=ret(15000);const velocity=r2/2,accel=r1-r2/2,score=.45*velocity+.35*accel+.20*(r5/5)-.04*Math.max(0,Math.abs(r15)-1.5);return{symbol:s,price:p,r1,r2,r5,r15,velocity,accel,score}}
function counts(){let l=0,s=0;for(const p of pos.values())p.side==="LONG"?l++:s++;return{l,s}}
function can(f){if(pos.has(f.symbol))return false;const c=cool.get(f.symbol);if(c&&now()<c)return false;const n=counts(),side=f.score>0?"LONG":"SHORT";return pos.size<MAX_POS&&Math.abs(f.score)>=.002&&!(side==="LONG"&&n.l>=MAX_SIDE)&&!(side==="SHORT"&&n.s>=MAX_SIDE)}
function open(f){pos.set(f.symbol,{symbol:f.symbol,side:f.score>0?"LONG":"SHORT",entry:f.price,openedAt:now(),margin:MARGIN})}
function close(p,price,reason){const d=p.side==="LONG"?1:-1,move=(price/p.entry-1)*d,gross=p.margin*move*LEV,fees=p.margin*LEV*FEE*2,slip=p.margin*LEV*SLIP*2,net=gross-fees-slip;realized+=net;equity=START+realized;trades.push({symbol:p.symbol,side:p.side,entry:p.entry,exit:price,net,reason});cool.set(p.symbol,now()+COOLDOWN_MS);pos.delete(p.symbol)}
function manage(){for(const p of [...pos.values()]){const t=ticks.get(p.symbol);if(!t)continue;const d=p.side==="LONG"?1:-1,m=(t.price/p.entry-1)*d;if(m>=TP)close(p,t.price,"TP");else if(m<=-SL)close(p,t.price,"SL");else if(now()-p.openedAt>=HOLD)close(p,t.price,"TIME")}}
function scan(){const st=performance.now();scanNo++;manage();const a=[];for(const s of symbols.keys()){const f=feat(s);if(f)a.push(f)}a.sort((x,y)=>Math.abs(y.score)-Math.abs(x.score));topSignals=a.slice(0,20);for(const f of a.slice(0,40))if(can(f)){open(f);break}lastScanMs=performance.now()-st;lastScanAt=now()}
function state(){let u=0;for(const p of pos.values()){const t=ticks.get(p.symbol);if(t){const d=p.side==="LONG"?1:-1;u+=p.margin*((t.price/p.entry-1)*d)*LEV}}return{mode:"PAPER",markets:symbols.size,ticks:ticks.size,scanNo,lastScanMs:+lastScanMs.toFixed(2),lastScanAt,connected,equity:+(equity+u).toFixed(2),realized:+realized.toFixed(2),unrealized:+u.toFixed(2),positions:[...pos.values()],trades:trades.slice(-50).reverse(),topSignals,cooldowns:[...cool.values()].filter(x=>x>now()).length,errors}}
const page=`<!doctype html><html lang=es><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>GALAXI Global Scanner</title><style>body{font-family:Arial;background:#080d14;color:#e8eef7;padding:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:10px}.c,.p{background:#111a25;border:1px solid #263448;border-radius:12px;padding:14px;margin-bottom:12px}.b{font-size:24px;font-weight:bold}.m{color:#92a1b6;font-size:12px}table{width:100%;border-collapse:collapse;font-size:12px}td,th{padding:7px;border-bottom:1px solid #223044;text-align:right}td:first-child,th:first-child{text-align:left}.up{color:#55e6a5}.dn{color:#ff7184}.scroll{overflow:auto;max-height:400px}</style><h2>GALAXI — GLOBAL SCANNER PAPER</h2><div class=m>Binance público · sin API keys · sin órdenes reales</div><div class=grid><div class=c>Mercados<div id=m class=b>—</div></div><div class=c>Ticks<div id=t class=b>—</div></div><div class=c>Scan #<div id=n class=b>—</div></div><div class=c>Scan ms<div id=ms class=b>—</div></div><div class=c>Equity<div id=e class=b>—</div></div><div class=c>PnL<div id=p class=b>—</div></div><div class=c>Posiciones<div id=o class=b>—</div></div><div class=c>WS<div id=w class=b>—</div></div></div><div class=p><b>TOP MOVIMIENTOS ANTICIPADOS</b><div class=m>Velocidad + aceleración + persistencia; cooldown 5 min.</div><div class=scroll><table><thead><tr><th>PAR</th><th>SCORE</th><th>1s%</th><th>2s%</th><th>5s%</th><th>15s%</th></tr></thead><tbody id=s></tbody></table></div></div><div class=p><b>TRADES PAPER</b><div class=scroll><table><thead><tr><th>PAR</th><th>LADO</th><th>NETO</th><th>MOTIVO</th></tr></thead><tbody id=r></tbody></table></div></div><script>async function u(){try{const x=await fetch('/api/state').then(r=>r.json());m.textContent=x.markets;t.textContent=x.ticks;n.textContent=x.scanNo;ms.textContent=x.lastScanMs;e.textContent='$'+x.equity.toFixed(2);p.textContent='$'+x.realized.toFixed(2);o.textContent=x.positions.length;w.textContent=x.connected?'OK':'OFF';s.innerHTML=x.topSignals.map(a=>'<tr><td>'+a.symbol+'</td><td class='+(a.score>=0?'up':'dn')+'>'+a.score.toFixed(4)+'</td><td>'+a.r1.toFixed(3)+'</td><td>'+a.r2.toFixed(3)+'</td><td>'+a.r5.toFixed(3)+'</td><td>'+a.r15.toFixed(3)+'</td></tr>').join('');r.innerHTML=x.trades.map(a=>'<tr><td>'+a.symbol+'</td><td>'+a.side+'</td><td class='+(a.net>=0?'up':'dn')+'>'+a.net.toFixed(2)+'</td><td>'+a.reason+'</td></tr>').join('')}catch(e){}}setInterval(u,1000);u()</script>`;
const srv=http.createServer((q,r)=>{if(q.url==="/api/state"){r.writeHead(200,{"content-type":"application/json"});return r.end(JSON.stringify(state()))}r.writeHead(200,{"content-type":"text/html;charset=utf-8"});r.end(page)});
async function boot(){try{console.log("UNIVERSE",await universe())}catch(e){errors++;console.error("UNIVERSE_ERROR",e.message)}srv.listen(PORT,()=>console.log("GALAXI PAPER SCANNER",PORT));const ws=new WebSocket("wss://fstream.binance.com/ws/!miniTicker@arr");ws.on("open",()=>{connected=true;console.log("WS_CONNECTED=1")});ws.on("close",()=>connected=false);ws.on("error",()=>{errors++;connected=false});ws.on("message",raw=>{try{const a=JSON.parse(raw);if(Array.isArray(a)){const ts=now();for(const x of a)if(symbols.has(x.s))tick(x.s,Number(x.c),Number(x.q||0),ts)}}catch{errors++}});setInterval(scan,SCAN_MS)}boot();